// Writes src/holidays.ts: the days the critter wears its holiday hat (spec section 4), worked out
// from the Hebrew calendar with the ICU data Node ships. The app's JavaScript engines can't be
// counted on to know the Hebrew calendar, so the dates are generated once and committed.
// Run: node scripts/holidays.ts [first year] [last year]
import { writeFileSync } from 'node:fs';
import { join } from 'node:path';

const first = Number(process.argv[2] ?? 2026);
const last = Number(process.argv[3] ?? 2036);
const hebrew = new Intl.DateTimeFormat('en-u-ca-hebrew', { month: 'long', day: 'numeric', timeZone: 'UTC' });

function hebrewDate(day: Date): { month: string; date: number } {
  const parts = hebrew.formatToParts(day);
  return {
    month: parts.find((part) => part.type === 'month')?.value ?? '',
    date: Number(parts.find((part) => part.type === 'day')?.value),
  };
}

/** The holiday a day belongs to, if any. */
function holiday(day: Date): string | null {
  const { month, date } = hebrewDate(day);
  const iso = day.toISOString().slice(5, 10);
  if (iso === '12-31' || iso === '01-01') return 'new-year';
  if (month === 'Tishri' && date <= 2) return 'rosh-hashanah';
  // Hanukkah: 25 Kislev and the seven days after it, into Tevet.
  if (month === 'Kislev' && date >= 25) return 'hanukkah';
  if (month === 'Tevet' && date <= 3) {
    const kislevEnd = new Date(day.getTime() - date * 86_400_000);
    const kislevLength = hebrewDate(kislevEnd).date;
    if (date <= 8 - (kislevLength - 24)) return 'hanukkah';
  }
  // Purim: 14 Adar, or 14 Adar II in a leap year.
  if ((month === 'Adar' || month === 'Adar II') && date === 14) return 'purim';
  if (month === 'Nisan' && date >= 15 && date <= 21) return 'passover';
  return null;
}

const ranges: Array<[string, string, string]> = [];
for (let day = new Date(Date.UTC(first, 0, 1)); day.getUTCFullYear() <= last; day = new Date(day.getTime() + 86_400_000)) {
  const name = holiday(day);
  const iso = day.toISOString().slice(0, 10);
  const previous = ranges.at(-1);
  if (!name) continue;
  const yesterday = new Date(day.getTime() - 86_400_000).toISOString().slice(0, 10);
  if (previous && previous[2] === name && previous[1] === yesterday) previous[1] = iso;
  else ranges.push([iso, iso, name]);
}

const lines = ranges.map(([start, end, name]) => `  ['${start}', '${end}'], // ${name}`);
const source = `// Generated by scripts/holidays.ts from the Hebrew calendar; do not edit by hand.
/** Holiday date ranges (first and last day, inclusive), ${first} to ${last}. */
export const HOLIDAYS: readonly (readonly [string, string])[] = [
${lines.join('\n')}
];

/** Whether a calendar day (YYYY-MM-DD) is a holiday, when the critter wears its holiday hat. */
export function isHoliday(day: string): boolean {
  return HOLIDAYS.some(([start, end]) => day >= start && day <= end);
}
`;
writeFileSync(join(import.meta.dirname, '../src/holidays.ts'), source);
console.log(`wrote ${ranges.length} holiday ranges`);
